### ISSUE TITLE
Auto-logout users

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stkaddons#42]
If stk aborts, users are not logged out properly, and appear to be still logged in (see https://github.com/supertuxkart/stk-code/issues/1868). While there might be a bug in stk (e.g. time out for login too small, so it does not have time to log out before stk exits), we need a cron job (? or something similar) which cleans up logged in users who have been idle (i.e. not send a poll request) for a certain amount of time.

**Comment by leyyin** [comment]
Should be fixed: leyyin@8f063ea1
