### ISSUE TITLE
Statistics improvements and bugs

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stkaddons#43]
http://addons.supertuxkart.net/stats/ has some problems in the 'clients' graph: the date at the bottom is: Dec 14   Dec 14  Dec  14  Jan 15  Jan 15, but no day :)

Showing the number of users online would be interesting, too (if keeping track of this stats, which would likely require a separate table is too much, just getting the number of currently logged in users would be nice)

**Comment by leyyin** [comment]
Both issues should be fixed. http://addons.supertuxkart.net/stats/
