### ISSUE TITLE
Leyyin's Addons fork: Profile URL can be javascript code

### ISSUE THREAD

**Issue by tomreyn** [supertuxkart/stkaddons#44]
I'm reporting here what was [initially posted to the wrong issue tracker](https://github.com/supertuxkart/stk-code/issues/1953):

> The profile URL (users' homepage) can be a javascript: initiated URL. allowing users to inject client side script code into the DOM. Look at the homepage given for the ["demo" user](http://addons.supertuxkart.net/users.php?user=demo) for an example.

**Comment by leyyin** [comment]
Should be fixed: leyyin@489b0660f
