### ISSUE TITLE
Leyyin's Addons fork: Duplicate encoding of user input

### ISSUE THREAD

**Issue by tomreyn** [supertuxkart/stkaddons#45]
I'm reporting here what was [initially posted to the wrong issue tracker](https://github.com/supertuxkart/stk-code/issues/1952):

> On [Addons](http://addons.supertuxkart.net/), when users submit special characters as part of, for example, their full name, then these special characters are not encoded once but twice at the time you look at the users' profile page. Look at the "real name" field of the ["demo" user](http://addons.supertuxkart.net/users.php?user=demo) for an example.

**Comment by leyyin** [comment]
Should be fixed: leyyin@489b0660f
